import time

print("System Failure Imminent!")
time.sleep(2)
print("System reboot has been initiated...")
print()
print()
time.sleep(1)
print("...rebooting sensory system")
time.sleep(0.5)
print("...rebooting output motors")
time.sleep(0.5)
print("...rebooting hover engine")
time.sleep(1)
print()
print()
print("System Online!")
